[package]
name = "icon-baker"
version = "0.1.0"
authors = ["Gark Garcia <37553739+GarkGarcia@users.noreply.github.com>"]
edition = "2018"

[dependencies]
image = "0.21.0"
regex = "1"
zip = "0.5"
png_encode_mini = "0.1.2"
nsvg = "0.5.0"
ico = "0.1.0"
icns = "0.3.0"
crossterm = "0.7.0"